### ISSUE TITLE
Support Wild Cards in DB name

### ISSUE THREAD

**Issue by pradeepbhadani** [HotelsDotCom/waggle-dance#43]
_As a SysOps_
_I want WD to support regex in DB names_
_So that I can use regexp to whitelist multiple DBs_

Acceptance Criteria:
* interpret the db name in the whitelist as a regular expression match accordingly
* Able to whitelist user_abc,user_def like user_.*
* Able to whitelist ALL databases with wildcard `.*`

**Comment by patduin** [comment]
@pradeepbhadani the issue says "regexp" but you're ok with just * wild cards correct?

**Comment by pradeepbhadani** [comment]
@patduin No. I am suggesting to have regex and * wildcard. 
I will update the acceptance criteria. My bad, I should have made * wildcard explicit.

**Comment by patduin** [comment]
Can we stick to one, e.g. or we allow the db name to be a regex or we allow wildcards but not both will just make it a bit easier to implement and result would be the same

**Comment by courtsVII** [comment]
Regex will complicate the configuration significantly, I think we should stick to just wildcard, for example if we support regexes there will be clashes all over the place, say user whitelists a db called db and there are databases of the name mydb dbone etc etc there will be unexpected matches, they will have to specify patterns rather than simple strings

**Comment by patduin** [comment]
we need to do full matches not partial matches.
We're going for regexp  I'll update the issue
